Parameters:
  Ami:
    Type: String
    Description: Latest AWS Linux Ami in your AWS Region
    Default: ami-428aa838

  InstanceType:
    Type: String
    Default: t2.small

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to instances

  SubnetID1:
    Type: String

  VpcId:
    Type: String

  SecurityGroupId:
    Type: String

Resources:
  HostRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - dynamodb.amazonaws.com
            - cloudformation.amazonaws.com
            - s3.amazonaws.com
            - lambda.amazonaws.com
            - rds.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-Admin
        PolicyDocument:
          Statement:
          - Action: "*"
            Resource: "*"
            Effect: Allow

  HostProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: HostRole

  Bastion:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: Ami
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: HostProfile
      SubnetId:
        Ref: SubnetID1
      KeyName:
        Ref: KeyName
      SecurityGroupIds:
      - Ref: SecurityGroupId
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #cloud-config
            runcmd:
            - curl -s -L https://raw.githubusercontent.com/changli3/awsd-instance-scheduler/master/install-bastion.sh | bash